name: Build & Deploy Portfolio

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: godwindev1/portfolio-app
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          # This ensures your build uses Ubuntu 24.04 as the base if your Dockerfile is set up correctly
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server & Update Stack
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/Devops-tools
            # Pull the latest image
            docker compose pull godwindev1/portfolio-app
            # Restart only the app container without dropping the DB
            docker compose -f Portfolio.yml up -d 
            # Optional: Clean up old unused images to save space on VPS
            docker image prune -f